workflows:
  ios:
    name: iOS build
    environment:
      cocoapods: default
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          brew install cocoapods
    ios:
      build_configuration: release
      export_method: development
