workflows:
  ios_build:
    name: iOS Build
    environment:
      cocoapods: default
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          brew install cocoapods
    ios:
      configuration: release
      export_method: development
