workflows:
  ios-build:
    name: iOS Build for GalleryCleaner
    max_build_duration: 120
    environment:
      xcode: latest
    scripts:
      - name: Install Dependencies
        script: |
          pod install || echo "No Podfile found, skipping..."
      - name: Build iOS App
        script: |
          xcodebuild -workspace GalleryCleaner.xcworkspace -scheme GalleryCleaner -sdk iphoneos -configuration Release archive -archivePath build/GalleryCleaner.xcarchive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive -archivePath build/GalleryCleaner.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath build/
    artifacts:
      - build/*.ipa
